export const REQUEST_ORDERS_PENDING = 'REQUEST_ORDERS_PENDING';
export const REQUEST_ORDERS_SUCCESS = 'REQUEST_ORDERS_SUCCESS';
export const CHANGE_ORDER_PENDING = 'CHANGE_ORDER_PENDING';
export const CHANGE_ORDER_SUCCESS = 'CHANGE_ORDER_SUCCESS';
export const DELETE_ORDER_PENDING = 'DELETE_ORDER_PENDING';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
