export const CHANGE_PIZZA_EDIT_FORM = 'CHANGE_PIZZA_EDIT_FORM';
export const CHANGE_FILE_INPUT = 'CHANGE_FILE_INPUT';
export const LOAD_PIZZA_EDIT = 'LOAD_PIZZA_EDIT';
export const EMPTY_PIZZA_EDIT = 'EMPTY_PIZZA_EDIT';
export const SET_EDIT_ID = 'SET_EDIT_ID';
export const SET_DELETE_ID = 'SET_DELETE_ID';
export const SET_MODIFICATION_TYPE = 'SET_MODIFICATION_TYPE';