export const REQUEST_PIZZAS_PENDING = 'REQUEST_PIZZAS_PENDING';
export const REQUEST_PIZZAS_SUCCESS = 'REQUEST_PIZZAS_SUCCESS';
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const FILTER_PIZZAS = 'FILTER_PIZZAS';
export const ADD_SHOPPINGCART = 'ADD_SHOPPINGCART';
export const DELETE_SHOPPINGCART = 'DELETE_SHOPPINGCART';
export const EMPTY_SHOPPINGCART = 'EMPTY_SHOPPINGCART';